### ISSUE TITLE
List of papers to be incorporated

### ISSUE THREAD

**Issue by willpearse** [willpearse/natdb#1]
The best way I can think of to keep an updated list of all the things to be incorporated is this Google Drive document: https://docs.google.com/spreadsheets/d/1J9t8nHJfY8qkMcdbm3PJKIwRqtQ8um_ED9FKFZbocUQ/edit?usp=sharing

I realise the ridiculousness of using such a thing on GitHub, but I really cannot bring myself to deal with a pull request every time someone finds a paper

**Comment by mahagadorn** [comment]
I'll just leave this right here...it might be useful
https://www.try-db.org/TryWeb/Publications.php

**Comment by willpearse** [comment]
This has made me very happy. Let's make sure to look for other sources too
though, as I'm friends with TRY people and I don't think we could to make
something as good as TRY in 24 hours...
