### ISSUE TITLE
Functions that don't work

### ISSUE THREAD

**Issue by willpearse** [willpearse/natdb#52]
Below is a list of the functions that don't work. This isn't a "list of shame", but figure out what's going on with your functions and check it off when it's done

- [ ] `.valido.2011`
- [ ] `.perez.2013`
- [ ] `.mesquita.2015`
- [ ] `.maire.2016`
- [ ] `.delgado.2015`
- [ ] `.abakumova.2016`
- [ ] `.tian.2016`
- [ ] `.McCullough.2015`

**Comment by mahagadorn** [comment]
.perez.2014

Error
``` 

> data <- read.xls(ft_get_si(‘10.5061/dryad.d61jk/1’, 'leaf traits, foliar freezing resistance, climatic niche.xlsx'), as.is=TRUE, sheet=1)
Error: unexpected input in "data <- read.xls(ft_get_si(�"

```

**Comment by mahagadorn** [comment]
.delaRiva.2015

Same issue as .perez.2014

**Comment by mahagadorn** [comment]
.tian.2016

Will this is one you said you would take a look at a while back.  The issue is how they have their NA data stored.  They contain odd characters.
