### ISSUE TITLE
Functions that need careful checking

### ISSUE THREAD

**Issue by willpearse** [willpearse/natdb#54]
- [ ] `.fitzgerald.2017`
- [ ] `.wright.2004`
- [ ] `.kamath.2016`
- [ ] `.husak.2016`
- [ ] `jennings.2016a` - this one is weird, as it's been duplicated but the two versions are different. Remember square root is x^1/2, log(mm), and abundance is #

**Comment by mahagadorn** [comment]
.arnold.2016

Need someone else to verify that these units are okay to use.  These descriptions come straight from paper.

"µLCO2/h"  =  routine metabolic rate: µL of CO2 per hour measured under resting condition, but allows for spontaneous activity

 "counts/h"  = activity measure: spontaneous activity during measurement of routine metabolic rate

**Comment by mahagadorn** [comment]
@willpearse There appears to be a repeat function but the dates are different

.philipson.2014 (the one I wrote)
.philipson.2016 

It looks like the same data set to me, but i didn't want to erase it.

**Comment by mahagadorn** [comment]
.kraft.2015a

Need someone else to verify that this unit are okay to use. These descriptions come straight from paper.

"J/m^-2" : Mean fracture toughness of leaf lamina (J m-2)

What would you call this?   the space in (J m-2) suggests multiplication but it is an average.  Suggestions?

**Comment by willpearse** [comment]
Averages have the same units as the thing they are the average of, so the Kraft ones are not a problem. That's a test of leaf puncture, in case you were wondering! :D
