### ISSUE TITLE
Use of fulltext::ft_get_si() with gdata::read.xls()

### ISSUE THREAD

**Issue by khafen74** [willpearse/natdb#60]
`ft_get_si()` is not working when used in conjunction with `read.xls()`, as shown for the functions below. `ft_get_si()` works when used in conjunction with `read.csv()` and `read.xls()` works when used without `ft_get_si()`. This could potentially be a problem with my machine. For each function, I've included the function name and the line of code that throws an error.

Error message
`Error in xls2sep(xls, sheet, verbose = verbose, ..., method = method,  : 
  Intermediate file 'C:\Users\konrad\AppData\Local\Temp\RtmpsF6ra0\file1df45a2e6a0f.csv' missing!`

kefi.2016
`data <- read.xls(ft_get_si("10.5061/dryad.b4vg0", "chilean_metadata.xls"), sheet = 1)`

maire.2016
`data <- read.xls(ft_get_si("10.5061/dryad.j42m7.2", "globamax_data_160609 (for GEB ms).xlsx"), sheet = "Data")`

These functions successfully download and read the files if I do not use `ft_get_si()`. grutters.2017, molinari.2014, and valido.2011 all use .xls(x) files from dryad and can be updated if this issue is fixed.

**Comment by willpearse** [comment]
I think this is specific to your machine; I can't get those files to load full stop. I've removed this function from the package; it's frustrating, because there's a lot of good stuff here, but if we can't get it to work then we can't get it to work. "Done is better than perfect" :-(
