### ISSUE TITLE
.ameztegui.2016 DOI not found...

### ISSUE THREAD

**Issue by bweedop** [willpearse/natdb#67]
When loading the data, an error is thrown because the DOI cannot be found. Run on a windows system.

**Comment by mrhelmus** [comment]
@willpearse @bweedop 
I am not certain where to put this, but it seems like the below error links to this issue and the issue that we just closed where read_excel() was substituted for read.xls(). 

I cannot download the .ameztegui.2016 data set. Here is the part of the code that gives the error:

```
read_excel(suppdata("10.5061/dryad.12b0h/2","FunctionalTraits_Dryad.xlsx"))
Error in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  : 
  Evaluation error: error -103 with zipfile in unzGetCurrentFileInfo
```

I looked on dryad and the link and file are correct. Perhaps it has to do with what suppdata returns which is this:
```
[1] "C:\\Users\\REDACT\\AppData\\Local\\Temp\\RtmpKQkwwE/10.5061_dryad.12b0h_2_FunctionalTraits_Dryad.xlsx"
attr(,"suffix")
[1] "xlsx"
```
I also ran the code as an admin and got the same error...
