### ISSUE TITLE
where are the balls? install_github does not work.

### ISSUE THREAD

**Issue by mrhelmus** [willpearse/natdb#68]
I am getting this error when I try to install natdb... my guess is that the build is failing now?

Downloading GitHub repo willpearse/natbd@master
from URL https://api.github.com/repos/willpearse/natbd/zipball/master
Installation failed: Not Found (404)

Same is true for nacdb

Downloading GitHub repo pearselab/nacbd@master
from URL https://api.github.com/repos/pearselab/nacbd/zipball/master
Installation failed: Not Found (404)

**Comment by willpearse** [comment]
TYpoE: `install_github("willpearse/natdb") and `install_github("pearselab/nacdb")`

It's natDB and nacDB, not natBD and nacBD.

**Comment by willpearse** [comment]
I hope to goodness the build doesn't fail, but of course it could :-(

**Comment by mrhelmus** [comment]
ahh! yes of course. let me try it...

**Comment by mrhelmus** [comment]
ok it worked! Just needed to install the dependency testdat... which I am not certain how to add to your code otherwise I would fork and pull request.

install_github("ropensci/testdat")

**Comment by willpearse** [comment]
Magic. Good to hear, and phew!!!
