### ISSUE TITLE
Error, Do I Need to install Perl?

### ISSUE THREAD

**Issue by mrhelmus** [willpearse/natdb#69]
If this error is because of a TyPEo you can take away my R card!

I am unable to download a lot of the data sets on my PC. I think the error is coming from fulltext::ft_get_si or gdata::read.xls 

Example Code: 
```
mydats  <- c(".artacho.2015", ".vanier.2013", ".aubret.2012b")
dat <- natdb(datasets = mydats)

Error in findPerl(verbose = verbose) : 
  perl executable not found. Use perl= argument to specify the correct path.
Error in file.exists(tfn) : invalid 'file' argument
```
But this code without the 3rd dataset works fine:

```
mydats  <- c(".artacho.2015", ".vanier.2013")
dat <- natdb(datasets = mydats)

```
Note that these first two data sets use read.csv2 and read.delim not gdata::read.xls

**Comment by willpearse** [comment]
This is a `gdata` problem. Blast...

Ok, I'll try and fix this tomorrow morning - it should be quick as it's a
find-replace job (use read_xls instead or something).

**Comment by mrhelmus** [comment]
I am not certain if it is gdata as this code does not work on my computer. Is this because ft_get_si does not have a dryad option? 

```
  data <- read.csv(ft_get_si("10.5061/dryad.56cn4","Data File 3. Parent tree information.csv"))

Error in if (pub$prefix == "http://id.crossref.org/prefix/10.0000") stop("Cannot find publisher for DOI: ",  : 
  argument is of length zero
In addition: Warning message:
404: Resource not found. - (10.5061/dryad.56cn4) 
```
