### ISSUE TITLE
natdb_citations

### ISSUE THREAD

**Issue by mrhelmus** [willpearse/natdb#70]
It would be helpful if the user can see all the data sets that could be loaded by NATDB before trying to download all the data. Currently, natdb_citations is stored in sys.data to be used by citations(), but I suggest moving it (or just make a copy of it) to /data so that the user can call it directly as data natdb_citations.

I can make some changes and put in a pull request, but first I need a bit of a tutorial on how you maintain the package so I do not mess it up (i.e., do you use Roxygen or not etc.).

**Comment by willpearse** [comment]
Good idea! I'll make that change.

**Comment by willpearse** [comment]
Thank you for doing this Matt, and sorry for not noting that here... Closing issue.
