### ISSUE TITLE
citations.tsv last 4 entries, no first column (counter).

### ISSUE THREAD

**Issue by eliagbayani** [willpearse/natdb#94]
Dear willpearse,
The last 4 entries in the citations.tsv file don't have the first column, that seems a row counter that's missing.

https://onlinelibrary.wiley.com/doi/full/10.1111/jeb.12068
https://doi.org/10.5061/dryad.kf490/4

https://royalsocietypublishing.org/doi/pdf/10.1098/rsbl.2005.0428
https://doi.org/10.1098/rsbl.2005.0428

https://onlinelibrary.wiley.com/doi/full/10.1111/evo.12132
https://doi.org/10.5061/dryad.qj811/1

https://royalsocietypublishing.org/doi/full/10.1098/rsbl.2014.0043
10.1098/rsbl.2014.0043

**Comment by willpearse** [comment]
Quite right - thank you for spotting this!

>
